version: '3.9'

services:
  db:
    restart: unless-stopped
    environment:
      - "POSTGRES_PASSWORD=dev"
    ports:
      - "5432:5432"
    volumes:
      - 'db_data:/var/lib/postgresql/data'

volumes:
  db_data: ~